/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import Model.ModelStudent;
import Service.ServiceStudent;

/**
 *
 * @author luniz
 */
public class Create_Student extends javax.swing.JPanel {

    /**
     * Creates new form Create
     */
    public Create_Student() {
        initComponents();
    }

    public void loadData(ServiceStudent service, ModelStudent data) {

        if (data != null) {
            txtID.setText(data.getID_num() + " (Primary Key Uneditable)");
            txtID.setEditable(false);
            txtID.setEnabled(false);
            txtLname.setText(data.getLname());
            txtFname.setText(data.getFname());
            txtMname.setText(data.getMname());
            comboCourse.setSelectedItem(data.setCourse());
            txtMajor.setText(data.getMajor());

        }

    }

    public ModelStudent getData() {
        String ID_num = txtID.getText().trim().toUpperCase();
        String Lname = txtLname.getText().trim().toUpperCase();
        String Fname = txtFname.getText().trim().toUpperCase();
        String Mname = txtMname.getText().trim().toUpperCase();
        String course = comboCourse.getSelectedItem().toString();
        String Major = txtMajor.getText().trim().toUpperCase();

        return new ModelStudent(ID_num, Lname, Fname, Mname, course, Major);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMname = new javax.swing.JTextField();
        Courselb = new javax.swing.JLabel();
        Majorlb = new javax.swing.JLabel();
        txtMajor = new javax.swing.JTextField();
        comboCourse = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("ID Number");

        txtID.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Lastname");

        txtLname.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Firstname");

        txtFname.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Middlename");

        txtMname.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        Courselb.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Courselb.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Courselb.setText("Course");

        Majorlb.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Majorlb.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Majorlb.setText("Major");

        txtMajor.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        comboCourse.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        comboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSN", "BEED", "BSED", "BSIT", "BSHM", "BSBA", "BSAC" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(Courselb)
                    .addComponent(Majorlb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID)
                    .addComponent(txtLname)
                    .addComponent(txtFname)
                    .addComponent(txtMname)
                    .addComponent(comboCourse, 0, 264, Short.MAX_VALUE)
                    .addComponent(txtMajor))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Courselb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Majorlb)
                    .addComponent(txtMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboCourse, txtFname, txtID, txtLname, txtMajor, txtMname});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Courselb;
    private javax.swing.JLabel Majorlb;
    private javax.swing.JComboBox<Object> comboCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMajor;
    private javax.swing.JTextField txtMname;
    // End of variables declaration//GEN-END:variables
}
